// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: llmdocs.proto

package llmdocsclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestMetadata carries caller context attached to every request. All fields
// are optional today; future revisions may require some of them.
type RequestMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier for the caller (e.g. Developer Portal user UUID). Prefer
	// this over user_email for attribution when available.
	UserId    *string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	UserEmail *string `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3,oneof" json:"user_email,omitempty"`
	ProjectId *string `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	// Full semver of the Metaplay SDK the caller is running (e.g. "32.0.0-rc.1").
	SdkVersion    *string `protobuf:"bytes,4,opt,name=sdk_version,json=sdkVersion,proto3,oneof" json:"sdk_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
	mi := &file_llmdocs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetadata.ProtoReflect.Descriptor instead.
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMetadata) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *RequestMetadata) GetUserEmail() string {
	if x != nil && x.UserEmail != nil {
		return *x.UserEmail
	}
	return ""
}

func (x *RequestMetadata) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *RequestMetadata) GetSdkVersion() string {
	if x != nil && x.SdkVersion != nil {
		return *x.SdkVersion
	}
	return ""
}

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GrpcMethod    string                 `protobuf:"bytes,2,opt,name=grpc_method,json=grpcMethod,proto3" json:"grpc_method,omitempty"`
	HttpRoute     string                 `protobuf:"bytes,3,opt,name=http_route,json=httpRoute,proto3" json:"http_route,omitempty"`
	McpTool       string                 `protobuf:"bytes,4,opt,name=mcp_tool,json=mcpTool,proto3" json:"mcp_tool,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_llmdocs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{1}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetGrpcMethod() string {
	if x != nil {
		return x.GrpcMethod
	}
	return ""
}

func (x *Capability) GetHttpRoute() string {
	if x != nil {
		return x.HttpRoute
	}
	return ""
}

func (x *Capability) GetMcpTool() string {
	if x != nil {
		return x.McpTool
	}
	return ""
}

func (x *Capability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_llmdocs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{2}
}

func (x *GetCapabilitiesRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetCapabilitiesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceName    string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion string                 `protobuf:"bytes,2,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	Capabilities   []*Capability          `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_llmdocs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{3}
}

func (x *GetCapabilitiesResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_llmdocs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{4}
}

func (x *GetInfoRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DeploymentInfoJson string                 `protobuf:"bytes,1,opt,name=deployment_info_json,json=deploymentInfoJson,proto3" json:"deployment_info_json,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_llmdocs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{5}
}

func (x *GetInfoResponse) GetDeploymentInfoJson() string {
	if x != nil {
		return x.DeploymentInfoJson
	}
	return ""
}

type ReadFileRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Path     string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// 1-indexed line to start reading from. Defaults to line 1 if unset.
	Offset *int32 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	// Maximum number of lines to return from `offset`. Defaults to 2000 if
	// unset. When the returned content does not reach end of file it ends
	// with a footer telling the caller which lines were returned and what
	// offset to use to continue.
	Limit         *int32 `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_llmdocs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFileRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ReadFileRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_llmdocs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{7}
}

func (x *ReadFileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type FindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_llmdocs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{8}
}

func (x *FindRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FindRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *FindRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FindResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RenderedOutput string                 `protobuf:"bytes,2,opt,name=rendered_output,json=renderedOutput,proto3" json:"rendered_output,omitempty"`
	NoResults      bool                   `protobuf:"varint,3,opt,name=no_results,json=noResults,proto3" json:"no_results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	mi := &file_llmdocs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{9}
}

func (x *FindResponse) GetRenderedOutput() string {
	if x != nil {
		return x.RenderedOutput
	}
	return ""
}

func (x *FindResponse) GetNoResults() bool {
	if x != nil {
		return x.NoResults
	}
	return false
}

type RipgrepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Fixed         bool                   `protobuf:"varint,3,opt,name=fixed,proto3" json:"fixed,omitempty"`
	IgnoreCase    bool                   `protobuf:"varint,4,opt,name=ignore_case,json=ignoreCase,proto3" json:"ignore_case,omitempty"`
	LineNumbers   bool                   `protobuf:"varint,5,opt,name=line_numbers,json=lineNumbers,proto3" json:"line_numbers,omitempty"`
	Context       int32                  `protobuf:"varint,6,opt,name=context,proto3" json:"context,omitempty"`
	ContextAfter  int32                  `protobuf:"varint,7,opt,name=context_after,json=contextAfter,proto3" json:"context_after,omitempty"`
	ContextBefore int32                  `protobuf:"varint,8,opt,name=context_before,json=contextBefore,proto3" json:"context_before,omitempty"`
	FilesOnly     bool                   `protobuf:"varint,9,opt,name=files_only,json=filesOnly,proto3" json:"files_only,omitempty"`
	CountOnly     bool                   `protobuf:"varint,10,opt,name=count_only,json=countOnly,proto3" json:"count_only,omitempty"`
	Multiline     bool                   `protobuf:"varint,11,opt,name=multiline,proto3" json:"multiline,omitempty"`
	FileTypes     []string               `protobuf:"bytes,12,rep,name=file_types,json=fileTypes,proto3" json:"file_types,omitempty"`
	Globs         []string               `protobuf:"bytes,13,rep,name=globs,proto3" json:"globs,omitempty"`
	Path          string                 `protobuf:"bytes,14,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RipgrepRequest) Reset() {
	*x = RipgrepRequest{}
	mi := &file_llmdocs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RipgrepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RipgrepRequest) ProtoMessage() {}

func (x *RipgrepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RipgrepRequest.ProtoReflect.Descriptor instead.
func (*RipgrepRequest) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{10}
}

func (x *RipgrepRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RipgrepRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *RipgrepRequest) GetFixed() bool {
	if x != nil {
		return x.Fixed
	}
	return false
}

func (x *RipgrepRequest) GetIgnoreCase() bool {
	if x != nil {
		return x.IgnoreCase
	}
	return false
}

func (x *RipgrepRequest) GetLineNumbers() bool {
	if x != nil {
		return x.LineNumbers
	}
	return false
}

func (x *RipgrepRequest) GetContext() int32 {
	if x != nil {
		return x.Context
	}
	return 0
}

func (x *RipgrepRequest) GetContextAfter() int32 {
	if x != nil {
		return x.ContextAfter
	}
	return 0
}

func (x *RipgrepRequest) GetContextBefore() int32 {
	if x != nil {
		return x.ContextBefore
	}
	return 0
}

func (x *RipgrepRequest) GetFilesOnly() bool {
	if x != nil {
		return x.FilesOnly
	}
	return false
}

func (x *RipgrepRequest) GetCountOnly() bool {
	if x != nil {
		return x.CountOnly
	}
	return false
}

func (x *RipgrepRequest) GetMultiline() bool {
	if x != nil {
		return x.Multiline
	}
	return false
}

func (x *RipgrepRequest) GetFileTypes() []string {
	if x != nil {
		return x.FileTypes
	}
	return nil
}

func (x *RipgrepRequest) GetGlobs() []string {
	if x != nil {
		return x.Globs
	}
	return nil
}

func (x *RipgrepRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RipgrepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	NoResults     bool                   `protobuf:"varint,2,opt,name=no_results,json=noResults,proto3" json:"no_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RipgrepResponse) Reset() {
	*x = RipgrepResponse{}
	mi := &file_llmdocs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RipgrepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RipgrepResponse) ProtoMessage() {}

func (x *RipgrepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RipgrepResponse.ProtoReflect.Descriptor instead.
func (*RipgrepResponse) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{11}
}

func (x *RipgrepResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RipgrepResponse) GetNoResults() bool {
	if x != nil {
		return x.NoResults
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Keywords      []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_llmdocs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{12}
}

func (x *SearchRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_llmdocs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmdocs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_llmdocs_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_llmdocs_proto protoreflect.FileDescriptor

const file_llmdocs_proto_rawDesc = "" +
	"\n" +
	"\rllmdocs.proto\x12\n" +
	"llmdocs.v1\"\xd7\x01\n" +
	"\x0fRequestMetadata\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x88\x01\x01\x12\"\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tH\x01R\tuserEmail\x88\x01\x01\x12\"\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tH\x02R\tprojectId\x88\x01\x01\x12$\n" +
	"\vsdk_version\x18\x04 \x01(\tH\x03R\n" +
	"sdkVersion\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\r\n" +
	"\v_user_emailB\r\n" +
	"\v_project_idB\x0e\n" +
	"\f_sdk_version\"\x9d\x01\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vgrpc_method\x18\x02 \x01(\tR\n" +
	"grpcMethod\x12\x1d\n" +
	"\n" +
	"http_route\x18\x03 \x01(\tR\thttpRoute\x12\x19\n" +
	"\bmcp_tool\x18\x04 \x01(\tR\amcpTool\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"Q\n" +
	"\x16GetCapabilitiesRequest\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.llmdocs.v1.RequestMetadataR\bmetadata\"\xa1\x01\n" +
	"\x17GetCapabilitiesResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\x02 \x01(\tR\x0eserviceVersion\x12:\n" +
	"\fcapabilities\x18\x03 \x03(\v2\x16.llmdocs.v1.CapabilityR\fcapabilities\"I\n" +
	"\x0eGetInfoRequest\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.llmdocs.v1.RequestMetadataR\bmetadata\"C\n" +
	"\x0fGetInfoResponse\x120\n" +
	"\x14deployment_info_json\x18\x01 \x01(\tR\x12deploymentInfoJson\"\xab\x01\n" +
	"\x0fReadFileRequest\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.llmdocs.v1.RequestMetadataR\bmetadata\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x00R\x06offset\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\x05H\x01R\x05limit\x88\x01\x01B\t\n" +
	"\a_offsetB\b\n" +
	"\x06_limit\"@\n" +
	"\x10ReadFileResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"t\n" +
	"\vFindRequest\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.llmdocs.v1.RequestMetadataR\bmetadata\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"V\n" +
	"\fFindResponse\x12'\n" +
	"\x0frendered_output\x18\x02 \x01(\tR\x0erenderedOutput\x12\x1d\n" +
	"\n" +
	"no_results\x18\x03 \x01(\bR\tnoResults\"\xc8\x03\n" +
	"\x0eRipgrepRequest\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.llmdocs.v1.RequestMetadataR\bmetadata\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x14\n" +
	"\x05fixed\x18\x03 \x01(\bR\x05fixed\x12\x1f\n" +
	"\vignore_case\x18\x04 \x01(\bR\n" +
	"ignoreCase\x12!\n" +
	"\fline_numbers\x18\x05 \x01(\bR\vlineNumbers\x12\x18\n" +
	"\acontext\x18\x06 \x01(\x05R\acontext\x12#\n" +
	"\rcontext_after\x18\a \x01(\x05R\fcontextAfter\x12%\n" +
	"\x0econtext_before\x18\b \x01(\x05R\rcontextBefore\x12\x1d\n" +
	"\n" +
	"files_only\x18\t \x01(\bR\tfilesOnly\x12\x1d\n" +
	"\n" +
	"count_only\x18\n" +
	" \x01(\bR\tcountOnly\x12\x1c\n" +
	"\tmultiline\x18\v \x01(\bR\tmultiline\x12\x1d\n" +
	"\n" +
	"file_types\x18\f \x03(\tR\tfileTypes\x12\x14\n" +
	"\x05globs\x18\r \x03(\tR\x05globs\x12\x12\n" +
	"\x04path\x18\x0e \x01(\tR\x04path\"H\n" +
	"\x0fRipgrepResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1d\n" +
	"\n" +
	"no_results\x18\x02 \x01(\bR\tnoResults\"z\n" +
	"\rSearchRequest\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.llmdocs.v1.RequestMetadataR\bmetadata\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\"6\n" +
	"\x0eSearchResponse\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontentJ\x04\b\x01\x10\x02R\x04path2\xb4\x03\n" +
	"\vDocsService\x12Z\n" +
	"\x0fGetCapabilities\x12\".llmdocs.v1.GetCapabilitiesRequest\x1a#.llmdocs.v1.GetCapabilitiesResponse\x12B\n" +
	"\aGetInfo\x12\x1a.llmdocs.v1.GetInfoRequest\x1a\x1b.llmdocs.v1.GetInfoResponse\x12E\n" +
	"\bReadFile\x12\x1b.llmdocs.v1.ReadFileRequest\x1a\x1c.llmdocs.v1.ReadFileResponse\x129\n" +
	"\x04Find\x12\x17.llmdocs.v1.FindRequest\x1a\x18.llmdocs.v1.FindResponse\x12B\n" +
	"\aRipgrep\x12\x1a.llmdocs.v1.RipgrepRequest\x1a\x1b.llmdocs.v1.RipgrepResponse\x12?\n" +
	"\x06Search\x12\x19.llmdocs.v1.SearchRequest\x1a\x1a.llmdocs.v1.SearchResponseB,Z*github.com/metaplay/llm-docs/llmdocsclientb\x06proto3"

var (
	file_llmdocs_proto_rawDescOnce sync.Once
	file_llmdocs_proto_rawDescData []byte
)

func file_llmdocs_proto_rawDescGZIP() []byte {
	file_llmdocs_proto_rawDescOnce.Do(func() {
		file_llmdocs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llmdocs_proto_rawDesc), len(file_llmdocs_proto_rawDesc)))
	})
	return file_llmdocs_proto_rawDescData
}

var file_llmdocs_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_llmdocs_proto_goTypes = []any{
	(*RequestMetadata)(nil),         // 0: llmdocs.v1.RequestMetadata
	(*Capability)(nil),              // 1: llmdocs.v1.Capability
	(*GetCapabilitiesRequest)(nil),  // 2: llmdocs.v1.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil), // 3: llmdocs.v1.GetCapabilitiesResponse
	(*GetInfoRequest)(nil),          // 4: llmdocs.v1.GetInfoRequest
	(*GetInfoResponse)(nil),         // 5: llmdocs.v1.GetInfoResponse
	(*ReadFileRequest)(nil),         // 6: llmdocs.v1.ReadFileRequest
	(*ReadFileResponse)(nil),        // 7: llmdocs.v1.ReadFileResponse
	(*FindRequest)(nil),             // 8: llmdocs.v1.FindRequest
	(*FindResponse)(nil),            // 9: llmdocs.v1.FindResponse
	(*RipgrepRequest)(nil),          // 10: llmdocs.v1.RipgrepRequest
	(*RipgrepResponse)(nil),         // 11: llmdocs.v1.RipgrepResponse
	(*SearchRequest)(nil),           // 12: llmdocs.v1.SearchRequest
	(*SearchResponse)(nil),          // 13: llmdocs.v1.SearchResponse
}
var file_llmdocs_proto_depIdxs = []int32{
	0,  // 0: llmdocs.v1.GetCapabilitiesRequest.metadata:type_name -> llmdocs.v1.RequestMetadata
	1,  // 1: llmdocs.v1.GetCapabilitiesResponse.capabilities:type_name -> llmdocs.v1.Capability
	0,  // 2: llmdocs.v1.GetInfoRequest.metadata:type_name -> llmdocs.v1.RequestMetadata
	0,  // 3: llmdocs.v1.ReadFileRequest.metadata:type_name -> llmdocs.v1.RequestMetadata
	0,  // 4: llmdocs.v1.FindRequest.metadata:type_name -> llmdocs.v1.RequestMetadata
	0,  // 5: llmdocs.v1.RipgrepRequest.metadata:type_name -> llmdocs.v1.RequestMetadata
	0,  // 6: llmdocs.v1.SearchRequest.metadata:type_name -> llmdocs.v1.RequestMetadata
	2,  // 7: llmdocs.v1.DocsService.GetCapabilities:input_type -> llmdocs.v1.GetCapabilitiesRequest
	4,  // 8: llmdocs.v1.DocsService.GetInfo:input_type -> llmdocs.v1.GetInfoRequest
	6,  // 9: llmdocs.v1.DocsService.ReadFile:input_type -> llmdocs.v1.ReadFileRequest
	8,  // 10: llmdocs.v1.DocsService.Find:input_type -> llmdocs.v1.FindRequest
	10, // 11: llmdocs.v1.DocsService.Ripgrep:input_type -> llmdocs.v1.RipgrepRequest
	12, // 12: llmdocs.v1.DocsService.Search:input_type -> llmdocs.v1.SearchRequest
	3,  // 13: llmdocs.v1.DocsService.GetCapabilities:output_type -> llmdocs.v1.GetCapabilitiesResponse
	5,  // 14: llmdocs.v1.DocsService.GetInfo:output_type -> llmdocs.v1.GetInfoResponse
	7,  // 15: llmdocs.v1.DocsService.ReadFile:output_type -> llmdocs.v1.ReadFileResponse
	9,  // 16: llmdocs.v1.DocsService.Find:output_type -> llmdocs.v1.FindResponse
	11, // 17: llmdocs.v1.DocsService.Ripgrep:output_type -> llmdocs.v1.RipgrepResponse
	13, // 18: llmdocs.v1.DocsService.Search:output_type -> llmdocs.v1.SearchResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_llmdocs_proto_init() }
func file_llmdocs_proto_init() {
	if File_llmdocs_proto != nil {
		return
	}
	file_llmdocs_proto_msgTypes[0].OneofWrappers = []any{}
	file_llmdocs_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llmdocs_proto_rawDesc), len(file_llmdocs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llmdocs_proto_goTypes,
		DependencyIndexes: file_llmdocs_proto_depIdxs,
		MessageInfos:      file_llmdocs_proto_msgTypes,
	}.Build()
	File_llmdocs_proto = out.File
	file_llmdocs_proto_goTypes = nil
	file_llmdocs_proto_depIdxs = nil
}
