name: Build CLI

on:
  workflow_dispatch:
  push:

run-name: Build from ${{ github.head_ref || github.ref_name }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubicloud-standard-8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          show-progress: false # suppress the noisy progress status output

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Check go mod tidy
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: go mod tidy caused changes. Please run 'go mod tidy' locally and commit the changes."
            git status
            git diff
            exit 1
          fi

      - name: Build CLI
        run: go build .

      - name: Run unit tests
        run: go test ./...
