name: Publish Pages

on:
  push:
    branches:
      - main
      - dev/pages-ci # dev branch for easier iteration
    # Run on changes to install.sh and publish-pages.yml. Keeps the install.sh public URL up-to-date.
    paths:
      - install.sh
      - .github/workflows/publish-pages.yml
    # Trigger on version tags for official releases like '1.2.3' (but not for dev releases like '1.2.3-xyz').
    # Keeps the command reference up-to-date with latest official release.
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read     # to checkout your code
  pages: write       # to publish the Pages site
  id-token: write    # required by actions/deploy-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Copy the install.sh to be available publicly at https://metaplay.github.io/cli/install.sh.
      # GitHub Pages isn't throttled like the https://raw.githubusercontent.com/metaplay/cli/main/install.sh.
      - name: Prepare Pages output
        run: |
          # Copy install.sh into 'site/'
          mkdir site
          cp install.sh site/

      # Write the full command reference into the directory.
      # The docs are available at https://metaplay.github.io/cli/command-reference.md.
      # This is mainly intended for the documentation crawlers to have access to the CLI's
      # full command reference.
      - name: Write command reference
        run: |
          go run . dev show-commands --output-docs site/command-reference.md

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Show published URL
        run: echo "🎉 Site published at ${{ steps.deployment.outputs.page_url }}"
