name: Publish Pages

on:
  push:
    branches:
      - main
      - pages-ci
      - docs-dump # \todo temp
    # Only run on changes to install.sh and publish-pages.yml
    paths:
      - install.sh
      - .github/workflows/publish-pages.yml

permissions:
  contents: read     # to checkout your code
  pages: write       # to publish the Pages site
  id-token: write    # required by actions/deploy-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Pages output
        run: |
          # Copy install.sh into 'site/'
          mkdir site
          cp install.sh site/

      # Write the full command reference into the directory
      - name: Write command reference
        run: |
          go run . dev show-commands --output-docs site/command-reference.md

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Show published URL
        run: echo "🎉 Site published at ${{ steps.deployment.outputs.page_url }}"
